### PR TITLE
added LeNet-5 model for MNIST example.

### PR DESCRIPTION
**Pull request by t-k-**
The model uses pooling layers and is able to
achieve test accuracy for over 99%. It serves
as additional example on show how to specify
a typical CNN network structure.

### CODE REVIEW

**Comment by t-k-** [comment]
@borgwang I am wondering why in the cnn example you did not put a pooling layer where a typical cnn has? I know pooling layer is kind of generalized convolution layer, but it may cause some confusion for people who expect cnn to have pooling layers.

**Comment by t-k-** [comment]
My test results show the current default cnn in example folder can also achieve test accuracy over 99%, it is just we have more computation without max-pooling layer. There is an interesting post on removing pooling layer [here](https://www.quora.com/What-effects-on-a-ConvNet-does-removing-all-the-pooling-layers-have). One states that
> Also, the pooling layers have this interesting property to help get rid of translation/rotation. This way, you are able to detect easily that there is a cat in your picture, but you cannot know where it is nor how many cats there are.

**Comment by borgwang** [comment]
You can just replace the default cnn architecture with the classic LeNet-5.
I was debugging conv layers at that time, and therefore removed pooling layers to see if convolution behave properly.

**Comment by t-k-** [comment]
I see, I am going to commit and replace it completely.

**Pull request merged**
